apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db
  namespace: spring-petclinic
  labels:
    app.kubernetes.io/part-of: petclinic
type: Opaque
stringData:
  # Provisioned by Reddy via Terraform on AWS RDS (eu-north-1)
  MYSQL_HOST: "petclinic-mysql.cvg6o2mo8msp.eu-north-1.rds.amazonaws.com"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "petclinic"
  MYSQL_USER: "petclinic"
  MYSQL_PASSWORD: "bufrf0:RYjmoF#KjXK<[dZtS8PqZ"
  SPRING_DATASOURCE_URL: "jdbc:mysql://petclinic-mysql.cvg6o2mo8msp.eu-north-1.rds.amazonaws.com:3306/petclinic?useSSL=false&allowPublicKeyRetrieval=true"
