apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db
  namespace: spring-petclinic
  labels:
    app.kubernetes.io/part-of: petclinic
type: Opaque
stringData:
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "petclinic"
  MYSQL_USER: "petclinic"
  MYSQL_PASSWORD: "petclinicpassword123"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/petclinic?useSSL=false&allowPublicKeyRetrieval=true"
