apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db
  namespace: spring-petclinic
  labels:
    app.kubernetes.io/part-of: petclinic
type: Opaque
stringData:
  # Reddy will provide the RDS endpoint after running Terraform
  MYSQL_HOST: "petclinic-mysql.rds.eu-central-1.amazonaws.com"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "petclinic"
  MYSQL_USER: "petclinic"
  MYSQL_PASSWORD: "petclinicpassword123"
