apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spring-petclinic

resources:
  - 00-namespace.yaml
  - config-server/deployment.yaml
  - config-server/service.yaml
  - discovery-server/deployment.yaml
  - discovery-server/service.yaml
  - customers-service/deployment.yaml
  - customers-service/service.yaml
  - visits-service/deployment.yaml
  - visits-service/service.yaml
  - vets-service/deployment.yaml
  - vets-service/service.yaml
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - admin-server/deployment.yaml
  - admin-server/service.yaml
