apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: spring-petclinic
  labels:
    app: discovery-server
    app.kubernetes.io/name: discovery-server
    app.kubernetes.io/part-of: petclinic
spec:
  type: ClusterIP
  selector:
    app: discovery-server
  ports:
    - name: http
      protocol: TCP
      port: 8761
      targetPort: 8761
